### PR TITLE
add license title

### PR DESCRIPTION
**Pull request by waldyrious**
background: https://github.com/btcsuite/btcd/pull/717

### CODE REVIEW

**Comment by waldyrious** [comment]
Note: the comment at the head of this file is partially redundant ("a BSD-style license that can be found in the LICENSE file"), and actually contradictory to the license ("All rights reserved"). Furthermore, the copyright ownership ("The Go Authors") also contradicts with the contents of the actual license text.

Any insights on how to resolve these inconsistencies?

**Comment by davecgh** [comment]
OK

**Comment by waldyrious** [comment]
@davecgh please check the comment I left above :)

**Comment by davecgh** [comment]
Oh I just reviewed the changes and didn't read the comment.  I apologize.  So the original code was from the Go stdlib and that is why it keeps their license.  The code that we added for midstate calculations is what is licensed under our ISC license.

**Pull request merged**
